local_costmap:
   global_frame: odom 
   robot_base_frame: base_link
   update_frequency: 3.0
   publish_frequency: 2.0
   static_map: false
   rolling_window: true
   width: 3.0
   height: 3.0
   resolution: 0.02
   transform_tolerance: 2.0

   inflation_radius: 0.3
   cost_scaling_factor: 0.55
